// examples/react-sample-app/src/views/Counter.tsx
import React, {useCallback, useMemo} from 'react';
import {useSelector} from 'react-redux';
import {getContext} from 'redux-anno';

import {Counter as CounterModel} from 'sample-shared-models';

const CounterComp = React.memo(() => {
  // todo move to hook utils

  const defaultCtx = useMemo(getContext, []);

  const counterInst = useMemo(() => defaultCtx.getOneInstance(CounterModel), [defaultCtx]);

  const counterVal = useSelector(() => counterInst.count.value);

  const updateCounterVal = useCallback(
    (nextVal: number) => () => {
      counterInst.updateCount.dispatch(nextVal);
    },
    [counterInst]
  );

  return (
    <div>
      Global Counter {counterVal}
      <button onClick={updateCounterVal(counterVal + 1)}>UP</button>
      <button onClick={updateCounterVal(counterVal - 1)}>DOWN</button>
    </div>
  );
});

export default CounterComp;

// examples/vue-sample-app/src/views/Counter.vue
<template>
  <div>
    Global Counter {{counterVal}}
    <Button type="primary" @click="updateCounterVal(counterVal+1)">UP</Button>
    <Button type="secondary" @click="updateCounterVal(counterVal-1)">DOWN</Button>
  </div>

</template>

<script lang="ts">
import {mapState} from 'redux-vuex';
import {getContext} from 'redux-anno';
import {Button} from "ant-design-vue";
import {Counter as CounterModel} from 'sample-shared-models';
const defaultCtx = getContext();
const counterInst = defaultCtx.getOneInstance(CounterModel);

export default {
  name: "Global Counter",
  components:{
    Button
  },
  methods:{
    updateCounterVal(nextVal:number){
      counterInst.updateCount.dispatch(nextVal);
    }
  },
  setup(){
    return mapState({
      counterVal:()=>counterInst.count.value
    })
  }
}
</script>
